---
title: "Tiernet"
author: "Gauthier A."
date: "06/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(
  rio,        # importing data  
  here,       # relative file pathways
  readxl,     # read excel
  writexl,    # write excel
  #skimr,      # Exploring data
  janitor,    # data cleaning and tables
  lubridate,  # working with dates
  epikit,     # age_categories() function
  tidyverse,  # data management and visualization,
  #gtsummary,  # summary statistics and tests,
  #rstatix,    # summary statistics and statistical tests
  scales,     # easily convert proportions to percents  
  labelled,   # Variable and values labelling
  flextable,  # Format tables,
  sqldf,      #sql queries
  RODBC       # Odbc database connection
)


# use here from the here package
here <- here::here
# use clean_names from the janitor package
clean_names <- janitor::clean_names

# load functions used from R scripts
source_path <- here("R", "RScripts.R")
source(source_path,local = knitr::knit_global())

data_folder <- "data"
image_folder <- "images"
output_folder <- "output"

###############################################################################
#################   I. Importing & Exploring Data         #####################
###################   Version of Tier.net : 1.13.4      #######################
###############################################################################
```

```{r setup, include=FALSE}

con<-RODBC::odbcDriverConnect("Driver={Microsoft Access Driver (*.mdb)};DBQ=C:/Users/Gauthier Abdala/Documents/RWD/TierNet/data/TierDESBanguiEloge_20220422.mdb")

vis_raw <- RODBC::sqlFetch(con,"VIS") #Follow Up clinic Visit table
pat_raw <- RODBC::sqlFetch(con,"PAT") #Socio demographic char. & outcome table
lab_raw <- RODBC::sqlFetch(con,"LAB") #Laboratory data table
dem_raw <- RODBC::sqlFetch(con,"DEM") #Demographic information

#pregnancy_raw <- RODBC::sqlFetch(con,"PREGNANCY")  #Pregnancy information
tb_raw        <- RODBC::sqlFetch(con,"TB")         #Tuberculosis Information
vis_tb_raw    <- RODBC::sqlFetch(con,"VIS_TB")     #TB Visit Table
transfers_raw <- RODBC::sqlFetch(con,"TRANSFERS")  #Transfer In/Out Table
#vis_preg_raw  <- RODBC::sqlFetch(con,"VIS_PREG")   #Antenatal Care
#infant_raw    <- RODBC::sqlFetch(con,"INFANT")     #Labour and Delivery


#############################################################################
########################      II. Cleaning data    ##########################
#############################################################################


############# 1. Cleaning column names    #################
###########################################################

vis <- vis_raw %>% janitor::clean_names()
pat <- pat_raw %>% janitor::clean_names()
lab <- lab_raw %>% janitor::clean_names()
dem <- dem_raw %>% janitor::clean_names()

#pregnancy <- pregnancy_raw  %>% janitor::clean_names()
tb        <- tb_raw         %>% janitor::clean_names()
vis_tb    <- vis_tb_raw     %>% janitor::clean_names()
transfers <- transfers_raw  %>% janitor::clean_names()
#vis_preg  <- vis_preg_raw   %>% janitor::clean_names()
#infant    <- infant_raw     %>% janitor::clean_names()


####### 2. Select,add and/or re order/rename columns #######
############################################################
vis <- vis %>%
  select(patient, visit_dmy, tb_status, who_stage, next_visit_dmy)

pat <- pat %>%
  select(patient, cohort, facility, birth_dmy,gender, frsvis_dmy,hivp_dmy, haart,
         haart_dmy, fhv_stage_who, tb_fhv, method_into_art, transfer_in_dmy, outcome,
         outcome_dmy)

lab <- lab %>%
  select(patient, lab_dmy, lab_id, lab_v, lab_t, episode_type, episode_id)

dem <- dem %>%
  select(patient, folder_number)

tb <- tb %>%
  select(patient, reg_dmy, tb_start_dmy, tb_end_dmy, tb_outcome, episode_id)

vis_tb <- vis_tb %>%
  select(patient, visit_dmy, next_visit_dmy, episode_id)

transfers <- transfers %>%
  select(patient, episode_id, facility_from, facility_to, transfer_dmy, transfer_action)



################ 3. Cleaning empty/null values     ##########
#############################################################

vis <-trim_data_columns(vis)
vis[is.null(vis)  | vis == "NULL" | vis == ""] <- NA

pat <-trim_data_columns(pat)
pat[is.null(pat)  | pat == "NULL" | pat == ""] <- NA

lab <-trim_data_columns(lab)
lab[is.null(lab)  | lab == "NULL" | lab == ""] <- NA

dem <-trim_data_columns(dem)
dem[is.null(dem)  | dem == "NULL" | dem == ""] <- NA

tb <-trim_data_columns(tb)
tb[is.null(tb)  | tb == "NULL" | tb == ""] <- NA

vis_tb <-trim_data_columns(vis_tb)
vis_tb[is.null(vis_tb)  | vis_tb == "NULL" | vis_tb == ""] <- NA

transfers <-trim_data_columns(transfers)
transfers[is.null(transfers)  | transfers == "NULL" | transfers == ""] <- NA


################ 4. Convert columns classes      #############
##############################################################
#is.date <- function(x) inherits(x, 'Date') #Used to check of column is date


vis <- vis %>%
  mutate(across(.cols = everything(), .fns = as.character)) %>% #Convert all columns to character class
  mutate(
    visit_dmy = parse_date(visit_dmy,"%Y-%m-%d"),
    next_visit_dmy = parse_date(next_visit_dmy,"%Y-%m-%d"),
    who_stage = parse_number(who_stage)
  ) %>%
  mutate(
    visit_dmy = as.Date(as.numeric(visit_dmy),origin ="1970-01-01"),
    next_visit_dmy = as.Date(as.numeric(next_visit_dmy),origin ="1970-01-01")
    )


pat <- pat %>%
  mutate(across(.cols = everything(), .fns = as.character)) %>% #Convert all columns to character class
  mutate(
    birth_dmy = parse_date(birth_dmy,"%Y-%m-%d"),
    frsvis_dmy = parse_date(frsvis_dmy,"%Y-%m-%d"),
    hivp_dmy = parse_date(hivp_dmy,"%Y-%m-%d"),
    haart_dmy = parse_date(haart_dmy,"%Y-%m-%d"),
    transfer_in_dmy = parse_date(transfer_in_dmy,"%Y-%m-%d"),
    outcome_dmy = parse_date(outcome_dmy,"%Y-%m-%d"),
  ) %>%
  mutate(
    birth_dmy = as.Date(as.numeric(birth_dmy),origin ="1970-01-01"),
    frsvis_dmy = as.Date(as.numeric(frsvis_dmy),origin ="1970-01-01"),
    hivp_dmy = as.Date(as.numeric(hivp_dmy),origin ="1970-01-01"),
    haart_dmy = as.Date(as.numeric(haart_dmy),origin ="1970-01-01"),
    transfer_in_dmy = as.Date(as.numeric(transfer_in_dmy),origin ="1970-01-01"),
    outcome_dmy = as.Date(as.numeric(outcome_dmy),origin ="1970-01-01"),
    )

lab <- lab %>%
  mutate(across(.cols = everything(), .fns = as.character)) %>% #Convert all columns to character class
  mutate(
    lab_dmy = parse_date(lab_dmy,"%Y-%m-%d"),
    lab_v = parse_number(lab_v)
  ) %>%
  mutate(
    lab_dmy = as.Date(as.numeric(lab_dmy),origin ="1970-01-01")
    )


tb <- tb %>%
  mutate(across(.cols = everything(), .fns = as.character)) %>% #Convert all columns to character class
  mutate(
    reg_dmy = parse_date(reg_dmy,"%Y-%m-%d"),
    tb_start_dmy = parse_date(tb_start_dmy,"%Y-%m-%d"),
    tb_end_dmy = parse_date(tb_end_dmy,"%Y-%m-%d"),
  ) %>%
  mutate(
    reg_dmy = as.Date(as.numeric(reg_dmy),origin ="1970-01-01"),
    tb_start_dmy = as.Date(as.numeric(tb_start_dmy),origin ="1970-01-01"),
    tb_end_dmy = as.Date(as.numeric(tb_end_dmy),origin ="1970-01-01"),
    )

vis_tb <- vis_tb %>%
  mutate(across(.cols = everything(), .fns = as.character)) %>% #Convert all columns to character class
  mutate(
    visit_dmy = parse_date(visit_dmy,"%Y-%m-%d"),
    next_visit_dmy = parse_date(next_visit_dmy,"%Y-%m-%d"),
  ) %>%
  mutate(
    visit_dmy = as.Date(as.numeric(visit_dmy),origin ="1970-01-01"),
    next_visit_dmy = as.Date(as.numeric(next_visit_dmy),origin ="1970-01-01")
    )

transfers <- transfers %>%
  mutate(across(.cols = everything(), .fns = as.character)) %>% #Convert all columns to character class
  mutate(
    transfer_dmy = parse_date(transfer_dmy,"%Y-%m-%d")
  ) %>%
  mutate(
    transfer_dmy = as.Date(as.numeric(transfer_dmy),origin ="1970-01-01")
    )

# transfers <- transfers %>%
#   filter(transfer_dmy >as.Date("2017-12-31") & facility_from == "CH KABINDA")


################ 5. Cleaning duplicate rows      #############
##############################################################
pat[duplicated(pat),]
pat<-unique(pat)

vis_duplicate <-vis[duplicated(vis),]
vis<-unique(vis)

lab_duplicate <-lab[duplicated(lab),]
lab<-unique(lab)
#TODO Cleaning of lab data for same exame encoded same date, different values...

tb_duplicate <-tb[duplicated(tb),]
tb<-unique(tb)

vis_tb_duplicate <-vis_tb[duplicated(vis_tb),]
vis_tb<-unique(vis_tb)

transfers_duplicate <-transfers[duplicated(transfers),]
transfers<-unique(transfers)

################# 5. Merge tables                #################
##################################################################
vis_data <- left_join(vis,dem,"patient") %>%
  left_join(pat,"patient")


################# 6. Add variables/values labels    ##############
##################################################################
labelled::val_labels(vis_data$gender)  <-c("1" = "Male", "2" = "Female", "95" = NA, "99" = NA)
labelled::val_labels(vis_data$haart)   <-c("0" = "Not on ART", "1" = "on ART")
labelled::val_labels(vis_data$outcome) <-c("10"= "Deceased", "20" = "In care", "30" = "Transfered Out", "40" = "LTFU", "95" = "Unknown")
labelled::val_labels(vis_data$method_in_art_named) <-c("0" = "New", "1" = "Transfer In", "88" = NA )



```

```{r include=FALSE,fig.width=10}

#############################################################################
##############      III. Analyzing data/presenting    #######################

#############################################################################

############################# ACTIVE COHORT #################################
#############################################################################
reportind_period <-as.Date("2021/12/31")
lftup<-pat %>%
  filter(outcome =="20")


################# INITIATIONS WITH NO DIAGNOSTIC DATES ######################
#############################################################################
no_diag_date <- pat %>%
  filter(
          method_into_art == 0 & # Only new patients
           (haart == 1)) %>% #Patients on ART with no Diag Date
  dplyr::filter(haart_dmy>=as.Date("2021/01/01"))%>%
  mutate(
    quarter_year =
      quarter(haart_dmy, with_year = T),
    month_year   = format(as.Date(haart_dmy), "%Y-%m"),
    diagn_date = ifelse(is.na(hivp_dmy),"Sans Date Diag VIH","Avec Date Diag VIH" )
  ) %>%
  group_by(facility, month_year,diagn_date) %>%
  summarise(total = n())

no_diag_date %>%
  
  ggplot()+
  geom_bar(
    aes(x=month_year,y = total,fill=diagn_date),
    position = position_stack(),
    stat="identity",
    color = "#661a00",
    )+
  theme(
    #aspect.ratio = 1.3,
    legend.position = "bottom",
    axis.text.x = element_text(angle = 65,hjust = 1.0),
    legend.title = element_blank(),
  )+
  facet_grid(~facility)+
  labs(
    title = "Initiations ARV, Janvier 2021 - Mars 2022",
    x = "Période"
  )


############################ LAB RESULTS ####################################
#############################################################################
start_period <- as.Date("2022/01/01")
end_period   <- as.Date("2022/03/31")

lab_data <-data.frame(
  "lab_req" = c(340,109,153,69),
  "lab_res" = c(303,29,88,59)
)

vl_data <- lab %>%
  left_join(pat, "patient") %>%
  select(patient, lab_dmy, lab_id, lab_v, facility) %>%
  mutate(
    quarter_year =
      quarter(lab_dmy, with_year = T),
    month_year   = format(as.Date(lab_dmy), "%Y-%m")
  ) %>%
  
filter(lab_id == "RNA" &
         lab_dmy >= start_period & lab_dmy <= end_period)%>%
group_by(facility, quarter_year) %>%
  summarise(total_tier = n())

#bind columns
vl_data <- vl_data %>% bind_cols(lab_data) %>%
  select(facility, quarter_year, lab_req, lab_res, total_tier)

vl_data_long <- vl_data %>% pivot_longer(cols = c(lab_req, lab_res, total_tier))
  
vl_data_long %>%
  ggplot()+
  geom_bar(
    aes(x=name,y = value,fill=name),
     position = "stack",
     stat = "identity"
  )+
  facet_grid(~facility)+
  labs(
    title = "Demandes et réalisations CV, Janvier 2022 - Mars 2022",
    x = "Type",
    y = "Total"
  )+
  scale_fill_discrete(
    labels=c("Demandes Labo","Resulats Labo", "Resultats Labo Tier")
    )

```
