---
title: "KinTierAnalysis"
author: "Gauthier A."
date: '2022-05-27'
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(
  rio,        # importing data  
  here,       # relative file pathways
  readxl,     # read excel
  writexl,    # write excel
  #skimr,      # Exploring data
  janitor,    # data cleaning and tables
  lubridate,  # working with dates
  epikit,     # age_categories() function
  tidyverse,  # data management and visualization,
  #gtsummary,  # summary statistics and tests,
  #rstatix,    # summary statistics and statistical tests
  scales,     # easily convert proportions to percents  
  labelled,   # Variable and values labelling
  flextable,  # Format tables,
  sqldf,      #sql queries
  RODBC,      #Odbc database connection,
  XMLm,       #Read XML Files
  openxlsx    # Write to Excel
)


# use here from the here package
here <- here::here
# use clean_names from the janitor package
clean_names <- janitor::clean_names

# load functions used from R scripts
source_path <- here("R", "RScripts.R")
source(source_path,local = knitr::knit_global())

data_folder <- "data"
image_folder <- "images"
output_folder <- "output"

```

```{r setup, include=FALSE}

###############################################################################
#################   I. Importing & Exploring Data         #####################
###################   Version of Tier.net : 1.13.4      #######################
###############################################################################

con<-RODBC::odbcDriverConnect("Driver={Microsoft Access Driver (*.mdb)};DBQ=C:/Users/Gauthier Abdala/Documents/RWD/TierNet/data/TierDESKinshasa042022.mdb")

vis_raw <- RODBC::sqlFetch(con,"VIS") #Follow Up clinic Visit table
pat_raw <- RODBC::sqlFetch(con,"PAT") #Socio demographic char. & outcome table
lab_raw <- RODBC::sqlFetch(con,"LAB") #Laboratory data table
dem_raw <- RODBC::sqlFetch(con,"DEM") #Demographic information

pregnancy_raw <- RODBC::sqlFetch(con,"PREGNANCY")  #Pregnancy information
tb_raw        <- RODBC::sqlFetch(con,"TB")         #Tuberculosis Information
vis_tb_raw    <- RODBC::sqlFetch(con,"VIS_TB")     #TB Visit Table
transfers_raw <- RODBC::sqlFetch(con,"TRANSFERS")  #Transfer In/Out Table
vis_preg_raw  <- RODBC::sqlFetch(con,"VIS_PREG")   #Antenatal Care
infant_raw    <- RODBC::sqlFetch(con,"INFANT")     #Labour and Delivery


#############################################################################
########################      II. Cleaning data    ##########################
#############################################################################


############# 1. Cleaning column names    #################
###########################################################

vis <- vis_raw %>% janitor::clean_names()
pat <- pat_raw %>% janitor::clean_names()
lab <- lab_raw %>% janitor::clean_names()
dem <- dem_raw %>% janitor::clean_names()

pregnancy <- pregnancy_raw  %>% janitor::clean_names()
tb        <- tb_raw         %>% janitor::clean_names()
vis_tb    <- vis_tb_raw     %>% janitor::clean_names()
transfers <- transfers_raw  %>% janitor::clean_names()
vis_preg  <- vis_preg_raw   %>% janitor::clean_names()
infant    <- infant_raw     %>% janitor::clean_names()


####### 2. Select,add and/or re order/rename columns #######
############################################################
vis <- vis %>%
  select(patient, visit_dmy, tb_status, who_stage, next_visit_dmy,user_defined_visit_var2,user_defined_visit_var3)

pat <- pat %>%
  select(patient, cohort, facility, birth_dmy,gender, frsvis_dmy,hivp_dmy, haart,
         haart_dmy, fhv_stage_who, tb_fhv, method_into_art, transfer_in_dmy, outcome,
         outcome_dmy)

### start lab------------------------
lab <- lab %>%
  select(patient, lab_dmy, lab_id, lab_v, lab_t, episode_type, episode_id)

## Custom variables
vis_custom_var <-trim_data_columns(vis)

## Custom variable Crag Serique for Tier.net <1.12
custom_crag <- vis_custom_var %>%
  filter (user_defined_visit_var2!="") %>%
  inner_join(pat,"patient")%>%
  select(facility,visit_dmy,patient,user_defined_visit_var2) %>%
  mutate(
    lab_dmy=visit_dmy,
    lab_id ="CRAG",
    lab_v = NA,
    lab_t = case_when(
      startsWith(tolower(user_defined_visit_var2),"pa") ~ "",
      startsWith(tolower(user_defined_visit_var2),"pc") ~ "",
      startsWith(tolower(user_defined_visit_var2),"pn") ~ "",
      startsWith(tolower(user_defined_visit_var2),"nf") ~ "",
      startsWith(tolower(user_defined_visit_var2),"n") ~ "-",
      startsWith(tolower(user_defined_visit_var2),"p") ~ "+",
      TRUE~ ""
    ),
    episode_type = NA,
    episode_id  = NA
  ) %>%
  filter(
    # Only get data with crag values
    lab_t !=""
  ) %>%
  select(patient,lab_dmy,lab_id,lab_t,lab_v,episode_type,episode_id)

## Bind custom crag data to lab data
lab <- lab%>%
  rbind(custom_crag)
  

## Custom variables Tblam for Tier.net <1.12
custom_tblam <- vis_custom_var %>%
  filter (user_defined_visit_var3!="") %>%
  inner_join(pat,"patient")%>%
  select(facility,visit_dmy,patient,user_defined_visit_var3) %>%
  mutate(
    lab_dmy=visit_dmy,
    lab_id ="LAM",
    lab_v = NA,
    lab_t = case_when(
      startsWith(tolower(user_defined_visit_var3),"pa") ~ "",
      startsWith(tolower(user_defined_visit_var3),"pc") ~ "",
      startsWith(tolower(user_defined_visit_var3),"pn") ~ "",
      startsWith(tolower(user_defined_visit_var3),"nf") ~ "",
      startsWith(tolower(user_defined_visit_var3),"n") ~ "-",
      startsWith(tolower(user_defined_visit_var3),"p") ~ "+",
      TRUE~ ""
    ),
    episode_type = NA,
    episode_id  = NA
  ) %>%
  filter(
    # Only get data with crag values
    lab_t !=""
  ) %>%
  select(patient,lab_dmy,lab_id,lab_t,lab_v,episode_type,episode_id)

## Bind custom tblam data to lab data
lab <- lab%>%
  rbind(custom_tblam)
### ------------------------ end lab

dem <- dem %>%
  select(patient, folder_number)

tb <- tb %>%
  select(patient, reg_dmy, tb_start_dmy, tb_end_dmy, tb_outcome, episode_id)

vis_tb <- vis_tb %>%
  select(patient, visit_dmy, next_visit_dmy, episode_id)

transfers <- transfers %>%
  select(patient, episode_id, facility_from, facility_to, transfer_dmy, transfer_action)



################ 3. Cleaning empty/null values     ##########
#############################################################

vis <-trim_data_columns(vis)
vis[is.null(vis)  | vis == "NULL" | vis == ""] <- NA

pat <-trim_data_columns(pat)
pat[is.null(pat)  | pat == "NULL" | pat == ""] <- NA

lab <-trim_data_columns(lab)
lab[is.null(lab)  | lab == "NULL" | lab == ""] <- NA

dem <-trim_data_columns(dem)
dem[is.null(dem)  | dem == "NULL" | dem == ""] <- NA

tb <-trim_data_columns(tb)
tb[is.null(tb)  | tb == "NULL" | tb == ""] <- NA

vis_tb <-trim_data_columns(vis_tb)
vis_tb[is.null(vis_tb)  | vis_tb == "NULL" | vis_tb == ""] <- NA

transfers <-trim_data_columns(transfers)
transfers[is.null(transfers)  | transfers == "NULL" | transfers == ""] <- NA

## Check if any of the dataframes have missing values
colSums(is.na(vis))
colSums(is.na(pat))
colSums(is.na(lab))
colSums(is.na(dem))
colSums(is.na(tb))
colSums(is.na(vis_tb))
colSums(is.na(transfers))

################ 4. Convert columns classes      #############
##############################################################
#is.date <- function(x) inherits(x, 'Date') #Used to check of column is date


vis <- vis %>%
  mutate(across(.cols = everything(), .fns = as.character)) %>% #Convert all columns to character class
  mutate(
    visit_dmy = parse_date(visit_dmy,"%Y-%m-%d"),
    next_visit_dmy = parse_date(next_visit_dmy,"%Y-%m-%d"),
    who_stage = parse_number(who_stage)
  ) %>%
  mutate(
    visit_dmy = as.Date(as.numeric(visit_dmy),origin ="1970-01-01"),
    next_visit_dmy = as.Date(as.numeric(next_visit_dmy),origin ="1970-01-01"),
    vis_year = year(visit_dmy)
  )


pat <- pat %>%
  mutate(across(.cols = everything(), .fns = as.character)) %>% #Convert all columns to character class
  mutate(
    birth_dmy = parse_date(birth_dmy,"%Y-%m-%d"),
    frsvis_dmy = parse_date(frsvis_dmy,"%Y-%m-%d"),
    hivp_dmy = parse_date(hivp_dmy,"%Y-%m-%d"),
    haart_dmy = parse_date(haart_dmy,"%Y-%m-%d"),
    transfer_in_dmy = parse_date(transfer_in_dmy,"%Y-%m-%d"),
    outcome_dmy = parse_date(outcome_dmy,"%Y-%m-%d"),
  ) %>%
  mutate(
    birth_dmy = as.Date(as.numeric(birth_dmy),origin ="1970-01-01"),
    frsvis_dmy = as.Date(as.numeric(frsvis_dmy),origin ="1970-01-01"),
    hivp_dmy = as.Date(as.numeric(hivp_dmy),origin ="1970-01-01"),
    haart_dmy = as.Date(as.numeric(haart_dmy),origin ="1970-01-01"),
    transfer_in_dmy = as.Date(as.numeric(transfer_in_dmy),origin ="1970-01-01"),
    outcome_dmy = as.Date(as.numeric(outcome_dmy),origin ="1970-01-01"),
    ) %>%
  mutate(
     #Add enrollment date
    enrol_date = case_when(
      method_into_art =="1" ~ transfer_in_dmy,
      method_into_art =="0" ~ haart_dmy 
    ),
    #Add enrollment year
    enrol_year  = year(enrol_date)
  )

lab <- lab %>%
  mutate(across(.cols = everything(), .fns = as.character)) %>% #Convert all columns to character class
  mutate(
    lab_dmy = parse_date(lab_dmy,"%Y-%m-%d"),
    lab_v = parse_number(lab_v)
  ) %>%
  mutate(
    lab_dmy = as.Date(as.numeric(lab_dmy),origin ="1970-01-01")
    )


tb <- tb %>%
  mutate(across(.cols = everything(), .fns = as.character)) %>% #Convert all columns to character class
  mutate(
    reg_dmy = parse_date(reg_dmy,"%Y-%m-%d"),
    tb_start_dmy = parse_date(tb_start_dmy,"%Y-%m-%d"),
    tb_end_dmy = parse_date(tb_end_dmy,"%Y-%m-%d"),
  ) %>%
  mutate(
    reg_dmy = as.Date(as.numeric(reg_dmy),origin ="1970-01-01"),
    tb_start_dmy = as.Date(as.numeric(tb_start_dmy),origin ="1970-01-01"),
    tb_end_dmy = as.Date(as.numeric(tb_end_dmy),origin ="1970-01-01"),
    )

vis_tb <- vis_tb %>%
  mutate(across(.cols = everything(), .fns = as.character)) %>% #Convert all columns to character class
  mutate(
    visit_dmy = parse_date(visit_dmy,"%Y-%m-%d"),
    next_visit_dmy = parse_date(next_visit_dmy,"%Y-%m-%d"),
  ) %>%
  mutate(
    visit_dmy = as.Date(as.numeric(visit_dmy),origin ="1970-01-01"),
    next_visit_dmy = as.Date(as.numeric(next_visit_dmy),origin ="1970-01-01")
    )

transfers <- transfers %>%
  mutate(across(.cols = everything(), .fns = as.character)) %>% #Convert all columns to character class
  mutate(
    transfer_dmy = parse_date(transfer_dmy,"%Y-%m-%d")
  ) %>%
  mutate(
    transfer_dmy = as.Date(as.numeric(transfer_dmy),origin ="1970-01-01")
    )

# transfers <- transfers %>%
#   filter(transfer_dmy >as.Date("2017-12-31") & facility_from == "CH KABINDA")


################ 5. Cleaning duplicate rows      #############
##############################################################
pat[duplicated(pat),]
pat<-unique(pat)

vis_duplicate <-vis[duplicated(vis),]
vis<-unique(vis)

lab_duplicate <-lab[duplicated(lab),]
lab<-unique(lab)
#TODO Cleaning of lab data for same exame encoded same date, different values...

tb_duplicate <-tb[duplicated(tb),]
tb<-unique(tb)

vis_tb_duplicate <-vis_tb[duplicated(vis_tb),]
vis_tb<-unique(vis_tb)

transfers_duplicate <-transfers[duplicated(transfers),]
transfers<-unique(transfers)

################# 5. Merge tables                #################
##################################################################

patient_full <-left_join(pat,dem,"patient")

vis_data  <- left_join(vis,dem,"patient") %>%
  left_join(pat,"patient")

trans_data<- left_join(transfers,dem,"patient") %>%
  left_join(pat,"patient")


################# 6. Add variables/values labels    ##############
##################################################################
# labelled::val_labels(vis_data$gender)  <-c("1" = "Male", "2" = "Female", "95" = NA, "99" = NA)
# labelled::val_labels(vis_data$haart)   <-c("0" = "Not on ART", "1" = "on ART")
# labelled::val_labels(vis_data$outcome) <-c("10"= "Deceased", "20" = "In care", "30" = "Transfered Out", "40" = "LTFU", "95" = "Unknown")
# labelled::val_labels(vis_data$method_in_art_named) <-c("0" = "New", "1" = "Transfer In", "88" = NA )

```

```{r include=FALSE}

#############################################################################
##############      III. Analyzing data/presenting    #######################
#############################################################################

############################ CP PATIENT ANALYSIS ############################
#############################################################################

cp_start_date    <- as.Date("2016/01/01")
cp_end_date      <- as.Date("2021/12/31")
trans_in_var     <- "transfer in"
trans_out_var    <- "transfer out"
trans_out_periods<- c("0-6M","6-12M",">12M")

cp_pat <-patient_full%>%
  mutate(
    enrolment_date = case_when(
      method_into_art =="1" ~ transfer_in_dmy,
      method_into_art =="0" ~ haart_dmy 
    ),
    enrol_year  = year(enrolment_date)
  )%>%
  #filter(enrolment_date>=cp_start_date & enrolment_date<=cp_end_date)%>%
  #Get CP patients from CHK (Both Converted CP from CHK and new CP patients)
  filter(
    (startsWith(folder_number,"CP") | endsWith(folder_number,"/CP")) 
    & facility =="CH KABINDA"
  )

cp_vis_data   <- vis_data %>%
  mutate(
    enrolment_date = case_when(
      method_into_art =="1" ~ transfer_in_dmy,
      method_into_art =="0" ~ haart_dmy 
    ),
    enrol_quarter= quarter(enrolment_date, with_year = T),
    enrol_year = year(enrolment_date)
  )%>%
  #filter(visit_dmy>=cp_start_date & visit_dmy<=cp_end_date)%>%
  #Get CP patients visits from CHK (Both Converted CP from CHK and new CP patients)
  filter(
    (startsWith(folder_number,"CP") | endsWith(folder_number,"/CP")) 
    & facility =="CH KABINDA"
  )

cp_trans_data <- trans_data %>%
  mutate(
    enrolment_date = case_when(
      method_into_art =="1" ~ transfer_in_dmy,
      method_into_art =="0" ~ haart_dmy 
    ),
    enrol_quarter= quarter(enrolment_date, with_year = T),
    enrol_year = year(enrolment_date)
  )%>%
  
  #filter(enrolment_date>=cp_start_date & enrolment_date<=cp_end_date)%>%
  #Get CP patients from CHK (Both Converted CP from CHK and new CP patients)
  filter(
    (startsWith(folder_number,"CP") | endsWith(folder_number,"/CP")) 
    & facility =="CH KABINDA"
  ) %>%
  mutate(
    trans_cat = case_when(
      mapply(identical,facility_from,facility_to) & transfer_dmy > transfer_in_dmy ~ trans_out_var,
      mapply(identical,facility_from,facility_to) & method_into_art =="1" ~ trans_in_var,
      mapply(identical,facility,facility_from)  ~ trans_out_var,
      mapply(identical,facility,facility_to) ~ trans_in_var,
      TRUE ~ ""
    )
  ) %>%
  relocate(transfer_dmy, .after = last_col())%>% #Move variable to be last
  mutate(
    #Calculate period after which patient got transferred out after enrollment period
    trans_out_after = interval(enrolment_date,transfer_dmy) %/% days(1) / (365/12),
    out_aft_cat = case_when(
      trans_out_after>0 & trans_out_after <=6 ~  "0-6M",
      trans_out_after>6 & trans_out_after <=12 ~ "6-12M",
      trans_out_after>12 ~ ">12M",
      TRUE ~ ""
    )
  )
  
  cp_trans_data$trans_cat[cp_trans_data$trans_cat==""] <-NA
  cp_trans_data$out_aft_cat[cp_trans_data$out_aft_cat==""] <-NA


#### Enrollment data ####

#Q/ How do we define new vs transfer in patients when it comes to CP patients?

## Proportion of new patients and transfers in enrollment over time

prop_cp_patient_meth_art <-cp_pat %>%
  #filter(method_into_art==0)%>%
  filter(as.Date(enrolment_date)>=cp_start_date)%>%
  mutate(
    quarter_year = quarter(enrolment_date, with_year = T),
  )%>%
  group_by(quarter_year,method_into_art)%>%
  arrange(quarter_year)%>%
  summarise(total = n())

prop_cp_patient_sum <- prop_cp_patient_meth_art %>%
  group_by(quarter_year)%>%
  arrange(quarter_year)%>%
  summarise(total = sum(total,na.rm = TRUE))
  

prop_cp_patient_meth_art%>%
  ggplot()+
  geom_bar(
    stat = "identity",
    color = "#661a00",
    position = position_stack(reverse = FALSE),
    aes(x = quarter_year,y = total,fill = method_into_art,
    )
  )+
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 65,hjust = 1.0),
    legend.title = element_blank(),
  )+
  geom_smooth(
    aes(x=quarter_year,y = total,colour="Tendances enrollement CP"),
    data = prop_cp_patient_sum,
    method = "loess",
    formula = "y~x"
  )+
  scale_fill_manual(#Add custom colors to bar graph values
    values=c("0"="#ffa366","1"="#80d4ff"),
    labels = c("New","Transfer In")
  )+
  labs(
    title = stringr::str_glue("Enrollement des patients CP(New + Transfers In), {year(cp_start_date)} - {year(cp_end_date)}") ,
    x     = "Période",
    y     = "Total",
  )



enrol_per_year <- cp_pat %>%
  group_by(enrol_year)%>%
  summarise(
    total_enrol = n()
  )

cp_sum_enr <- cp_pat%>%
  mutate(
    enrol_year = year(enrolment_date)
  ) %>%
  group_by(enrol_year)%>%
  summarise(
    trans_art_lt_transin = sum((haart_dmy  < transfer_in_dmy),na.rm = TRUE),
    trans_pat            = sum(method_into_art=="1",na.rm = TRUE),
    new_frsv_lt_haart    = sum((frsvis_dmy < haart_dmy),na.rm = TRUE),
    new_pat              = sum((method_into_art =="0"),na.rm = TRUE),
    new_frsv_blank       = sum(is.na(frsvis_dmy) & method_into_art=="0",na.rm = TRUE),
    
  )

#### Patients in Care####
cp_year_rep_start <- cp_start_date %m-% months(3) #Cohort starting reporting period
cp_year_rep_end   <- cp_end_date   %m-% months(3) #Cohort ending reporting period

## Get patients last next appointments to determine lost to follow ups

cp_vis_last_nextapp_data <- cp_vis_data%>%
  arrange(patient,visit_dmy)%>%
  group_by(patient) %>%
  mutate(# Get previous last next appointment and missed appointment days for patient
    last_next_app = lag(next_visit_dmy),
    miss_app_days = visit_dmy - last_next_app
  ) %>%
  select(last_next_app,visit_dmy,miss_app_days,everything())

#Get enrolments from from 15 months before end period to 9 months after start of current period
cp_vis_cohort_data <- cp_vis_last_nextapp_data %>%
  filter(
    enrolment_date>=cp_year_rep_start & enrolment_date<=cp_year_rep_end &
    visit_dmy>=cp_year_rep_start & visit_dmy<=cp_year_rep_end
    ) %>%
  mutate(
    #Reporting year is + 3months considering the lag
    report_year = year(as.Date(enrolment_date %m+% months(3)))
  ) %>%
  arrange(patient,desc(visit_dmy))

#Get unique patients data (last visit in reporting period) to check for ltfup
cp_vis_cohort_u_data <- cp_vis_cohort_data[!duplicated(cp_vis_cohort_data[,4]),]

#Splitting visit data per reporting period (year in this case)
spl <-split(cp_vis_cohort_data,cp_vis_cohort_data$report_year)

cp_vis_cohort_u_data <-data.frame(matrix(ncol = 30,nrow = 0))
colnames(cp_vis_cohort_u_data) <- colnames(cp_vis_cohort_data)

#Loop through each reporting category and get unique patients
for(x in spl){
   cp_vis_cohort_u_data <-cp_vis_cohort_u_data%>%
   rbind(x[!duplicated(x[,4]),])
}
  

#### NEXT STEPSSSSS ####
#LOOK INTO HOW FILTERING IS DONE FOR VISITS PER REPORTING PERIOD
#ALGORITHM IS TO LOOK, FROM ENROLLMENTS IN A PERIOD (YEAR),
#HOW MANY WERE LOST TO FOLLOW UP IN THAT REPORTING PERIOD (YEAR)



cp_diff <- cp_pat %>%
  filter(method_into_art =="1" & haart_dmy != transfer_in_dmy)

### TRANSFERS 


## Get Transfers data for HIV only
cp_trans_data_hiv <- cp_trans_data %>%
  filter(is.na(tb_start_dmy))

## TRANSFER OUT ANALYSIS
## Look at transfers out from enrollment in each reporting period(year)
## Answer to question : After how long do patients get transferred out?



cp_trans_out_data <- cp_trans_data_hiv %>%
  filter(#Filter transfers out with transfer out period
    trans_cat == trans_out_var &!is.na(out_aft_cat)
    ) %>%
  
  select(enrol_year,folder_number,out_aft_cat) %>%
  pivot_wider(names_from = out_aft_cat,values_from = folder_number,values_fn = length) %>%
  relocate(enrol_year,trans_out_periods) #Change order of columns


cp_sum_trans_out_data <- left_join(enrol_per_year,cp_trans_out_data,"enrol_year")

#Replace NA with 0
#cp_sum_trans_out_data[is.na(cp_sum_trans_out_data)] <-0

#Plotting transfers out for the reporting period
cp_sum_trans_out_data %>%
  filter(enrol_year >= year(cp_start_date) & enrol_year <=year(cp_end_date)) %>%
  pivot_longer(cols = trans_out_periods, names_to = "category",values_to = "total") %>%
  #mutate(category = factor(category),levels(trans_out_periods)) %>%
  ggplot()+
  # geom_point(
  #   stat = "identity",
  #   mapping = aes(x = enrol_year,y = total_enrol),
  #   na.rm = TRUE,
  # ) +
  geom_bar(
    stat = "identity",
    mapping = aes(x = enrol_year,y =total, fill = fct_rev(factor(category,levels =trans_out_periods))),
    #width = .30,
    na.rm = TRUE,
  )+theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 0,hjust =0.5),
    legend.title = element_blank(),
  )+
  scale_fill_manual(#Add custom colors to bar graph values
    values=c("0-6M"="#80d4ff","6-12M"="#ffa366",">12M"="#ff8080"),
    labels = c("0-6M","6-12M",">12M")
  )+
  labs(
    title = stringr::str_glue("Transfer out des patients CP par période de transfert après enrollement, {year(cp_start_date)} - {year(cp_end_date)}") ,
    x     = "Période",
    y     = "Total",
  )




##Get patients(based on folder number) with more than one transfer (in or out)
cp_data_type <- cp_trans_data_hiv %>%
  group_by(trans_cat,patient)%>%
  summarise(
    tot = n()
  ) %>%
  filter(tot>1)

##Since there is very few patients that appear to have been transferred more than once,
##assumption: Each enrollment (new,transfer in) is treated as a "new patient"


#Patients in care data per year
  #Enrollment and how many stay afer 3M,6M,12M,>12M
```

```{r include=FALSE, fig.width=7.0}


############################## AHD PHC ANALYSIS ################################
################################################################################

#Get visits for patients that date of visit = date of art start date


#Q/ Do we need a time window for initiations or do we keep strict art_start_date==visit_date


###################### CD4 LAB DATA ##############################
##################################################################
#A/ Given that in Tier.net we encode results dates for lab tests, we should have a time window check
#TODO : Need to remove duplicates for CD4 data encoded twice for the same visit


###CD4 Lab Data
lab_data_cd4 <-lab %>%
  filter((lab_id =="CD4A") & !is.na(lab_v)) %>%
  mutate(
    cd4_category = age_categories(
      lab_v,
      breakers = c(0,200,1000)
    )
  )


#vis_cd4 <- left_join(vis_data,lab_data_cd4,c("patient"="patient","visit_dmy"="lab_dmy"))

###!!! Important to clarify CD4 time window (here +-7 days) based on result turnaround time and validity period before requesting
###!!! If there exists two CD4 within the time window, which one to pick? Most recent one?

vis_cd4 <- sqldf(
  "select vis.visit_dmy,vis.patient,vis.next_visit_dmy,vis.folder_number,vis.cohort,vis.facility,vis.birth_dmy,
    vis.gender,vis.frsvis_dmy,vis.haart,vis.haart_dmy,vis.method_into_art,vis.tb_status,vis.transfer_in_dmy,vis.outcome,vis.outcome_dmy,vis.enrol_date,vis.enrol_year,lab.lab_dmy,lab.lab_v,lab.cd4_category 
    from vis_data vis
    left join lab_data_cd4 lab 
      on vis.patient = lab.patient and
        lab.lab_dmy  between (vis.visit_dmy-7)  and (vis.visit_dmy + 7) 
  "
)%>%
  rename(
    cd4_date = lab_dmy,
    cd4_value= lab_v
  )
 
#Filter duplicate lab results based on CD4 lab date
vis_cd4<-vis_cd4 %>%
  arrange(desc(cd4_date))

#Unique visits
#vis_cd4_data_dup<-vis_cd4[duplicated(vis_cd4[,1:16]),]
vis_cd4_data<-vis_cd4[!duplicated(vis_cd4[,1:16]),]

#Some duplicate visit data include
#Visits with different lab dates based on time window, need to decide which one to pick (soonest maybe?)
# 
# vis_cd4_data[!duplicated(vis_cd4_data[,1:16]),] %>%
#   arrange(patient)

###################### CRAG LAB DATA ##############################
##################################################################


lab_data_crag <-lab %>%
  filter((lab_id =="CRAG") & !is.na(lab_t)) 

vis_cd4_crag <- sqldf(
  "select cd4d.*,crag.lab_dmy,crag.lab_t
    from vis_cd4_data cd4d
    left join lab_data_crag crag
      on cd4d.patient = crag.patient
        and crag.lab_dmy between(cd4d.cd4_date -7) and(cd4d.cd4_date +7)
  "
)%>%
  rename(
    crag_date = lab_dmy,
    crag_value= lab_t
  )

vis_cd4_crag<-vis_cd4_crag %>%
  arrange(desc(crag_date))

#Unique visits
#vis_cd4_crag_data_dup<-vis_cd4_crag[duplicated(vis_cd4_crag[,1:19]),]
vis_cd4_crag_data<-vis_cd4_crag[!duplicated(vis_cd4_crag[,1:19]),]


###################### TBLAM LAB DATA ##############################
####################################################################

lab_data_tblam <-lab %>%
  filter((lab_id =="LAM") & !is.na(lab_t)) 

vis_cd4_crag_tbm <- sqldf(
  "select cd4crag.*,tb.lab_dmy,tb.lab_t
    from vis_cd4_crag_data cd4crag
    left join lab_data_tblam tb
      on cd4crag.patient = tb.patient
        and tb.lab_dmy between(cd4crag.cd4_date -7) and(cd4crag.cd4_date +7)
  "
)%>%
  rename(
    tbm_date = lab_dmy,
    tbm_value= lab_t
  )

vis_cd4_crag_tbm<-vis_cd4_crag_tbm %>%
  arrange(desc(tbm_date))

#Unique visits
#vis_cd4_crag_tbm_data_dup<-vis_cd4_crag_tbm[duplicated(vis_cd4_crag_tbm[,1:21]),]
vis_cd4_crag_tbm_data<-vis_cd4_crag_tbm[!duplicated(vis_cd4_crag_tbm[,1:21]),]


###################### LAST VL DATA #################################
#####################################################################

lab_data_vl <-lab %>%
  filter((lab_id =="RNA") & !is.na(lab_v))

#Get last VL up to 15 months(390 days) before current visit
#Assumption: Patient under care should have VL atleast once a year
vis_cd4_crag_tbm_lvl<-sqldf(
  "select data.*,vl.lab_dmy,vl.lab_v
    from vis_cd4_crag_tbm_data data
    left join lab_data_vl vl
      on data.patient = vl.patient
        and vl.lab_dmy between (data.visit_dmy -390) and (data.visit_dmy -1)"
)%>%
  rename(
    lastvl_date = lab_dmy,
    lastvl_value= lab_v
  )

vis_cd4_crag_tbm_lvl<-vis_cd4_crag_tbm_lvl %>%
  arrange(desc(lastvl_date))

#Unique visits
#vis_cd4_crag_tbm_lvl_data_dup<-vis_cd4_crag_tbm_lvl[duplicated(vis_cd4_crag_tbm_lvl[,1:23]),]
vis_cd4_crag_tbm_lvl_data<-vis_cd4_crag_tbm_lvl[!duplicated(vis_cd4_crag_tbm_lvl[,1:23]),]



  
## Remove unused/intermediate objects from memory

rm(list = c("vis_cd4","vis_cd4_data",
            "lab_data_crag","vis_cd4_crag","vis_cd4_crag_data",
            "lab_data_tblam","vis_cd4_crag_tbm","vis_cd4_crag_tbm_data",
            "lab_data_vl","vis_cd4_crag_tbm_lvl"))

###################### LAST CD4 DATA #################################
######################################################################

#Get last CD4 for patient
#Assumption: CD4 within 3 months of current visit may still be valid

vis_cd4_crag_tbm_lvl_l3cd4<-sqldf(
  "
    select data.*,cd4.lab_dmy,cd4.lab_v
    from vis_cd4_crag_tbm_lvl_data data
    left join lab_data_cd4 cd4
      on data.patient = cd4.patient
        and cd4.lab_dmy between (data.visit_dmy -90) and (data.visit_dmy-1)
  "
)%>%
  rename(
    last3cd4_date = lab_dmy,
    last3cd4_value= lab_v
  )

vis_cd4_crag_tbm_lvl_l3cd4<-vis_cd4_crag_tbm_lvl_l3cd4 %>%
  arrange(desc(last3cd4_date))

#Unique visits
#vis_cd4_crag_tbm_lvl_l3cd4_data_dup<-vis_cd4_crag_tbm_lvl_l3cd4[duplicated(vis_cd4_crag_tbm_lvl_l3cd4[,1:25]),]
vis_cd4_crag_tbm_lvl_l3cd4_data<-vis_cd4_crag_tbm_lvl_l3cd4[!duplicated(vis_cd4_crag_tbm_lvl_l3cd4[,1:25]),]


################## LAST NEXT APPOINTMENT DATA ########################
######################################################################

vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_data <- vis_cd4_crag_tbm_lvl_l3cd4_data %>%
  arrange(patient,visit_dmy)%>%
  group_by(patient) %>%
  mutate(# Get previous last next appointment and missed appointment days for patient
    last_next_app = lag(next_visit_dmy),
    miss_app_days = visit_dmy - last_next_app
  ) %>%
  select(last_next_app,visit_dmy,miss_app_days,everything())

#object.size(vis_cd4_crag_tbm_lvl_l3cd4_data)

########################## TRANSFER DATA #############################
######################################################################
#Add Transfers information to visit data
vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans <-vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_data%>%
  left_join(transfers,c("patient"="patient","visit_dmy"="transfer_dmy"))

vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans<-vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans %>%
  arrange(desc(visit_dmy))%>%
  #Move episode_id at the end
  relocate(episode_id,.after = last_col())

#Remove duplicate lines for transfers
#vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data_dup<-vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans[duplicated(vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans[,1:31]),]
#Note: This will include transfers in and transfers out that happened the same day as two separate lines
vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data<-vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans[!duplicated(vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans[,1:31]),]

#Adding a transfer category, transfer in or out
vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data<- vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data%>%
  mutate(
    trans_cat = case_when(
      mapply(identical,facility,facility_from)  ~ "transfer out",
      mapply(identical,facility,facility_to)  ~ "transfer in",
      TRUE ~ ""
    )
  )

## Remove unused/intermediate objects from memory

# rm(list = c("vis_cd4_crag_tbm_lvl_l3cd4","vis_cd4_crag_tbm_lvl_l3cd4_data",
#             "vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_data","vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans"))


################################################################################
############################ ELIBILITY CRITERIA ################################
################################################################################


start_period <-as.Date("2021/01/01")
end_period   <-as.Date("2021/12/31")
pat_col_ind  <- 4 #Patient column index in the data frame
days_ltfup   <-90 #Days for ltfu. This can be context specific

#Summary data for AHD cascade
summ_data_ahd <-data.frame(matrix(nrow = 0,ncol=14))
col_names <- c("category","eligible","cd4_done","%cd4_done","cd4_lt200","%cd4_lt200",
               "lam_done","%lam_done","crag_done_","%crag_done","lam_pos","%lam_pos",
               "crag_pos","%crag_pos")
colnames(summ_data_ahd) <-col_names

vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data <- vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
  mutate(
    vis_quarter_year = quarter(visit_dmy, with_year = T),
    vis_month_year   = format(as.Date(visit_dmy), "%Y-%m"),
  )

###########################  NEW INITIATIONS   #################################
################################################################################



# Filter visits where visit date == ART Start Date (new art initiations) and new patients,
# i.e. method_into_art == 0(not transfers in)

new_init <-vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
  filter( 
    (visit_dmy>=start_period & visit_dmy<=end_period)
    #New initiations filtering
    & (visit_dmy == haart_dmy & method_into_art == 0)
  )
new_init_data <- new_init[!duplicated(new_init[,6:20]),]

#Get unique patient codes with no CD4 to be used to avoid duplicate patients
new_init_pat_code <- unique(new_init_data$patient)

#Bind rows to summary data
summ_data_ahd <- summ_data_ahd %>%
  rbind(
    new_init_data %>%
       mutate(
        vis_year = year(visit_dmy)
      )%>%
      mutate(
        category    = "new art initiations",
      )%>%
      group_by(facility,category) %>%
      summarise(
        eligible    = n(),
        cd4_done    = sum(!is.na(cd4_value),na.rm = TRUE),
        `%cd4_done` = round((cd4_done/eligible),4)*100, 
        cd4_lt200   = sum(cd4_value<200,na.rm = TRUE),
        `%cd4_lt200`= round((cd4_lt200/cd4_done),4)*100,
        lam_done    = sum(cd4_value<200 & !is.na(tbm_value),na.rm = TRUE),
        `%lam_done` = round((lam_done/cd4_lt200),4)*100,
        crag_done   = sum(cd4_value<200 & !is.na(crag_value),na.rm = TRUE),
        `%crag_done`= round((crag_done/cd4_lt200),4)*100,
        lam_pos     = sum(cd4_value<200 & !is.na(tbm_value) & (tbm_value=="+"),na.rm = TRUE),
        `%lam_pos`  = round((lam_pos/lam_done),4)*100,
        crag_pos    = sum(cd4_value<200 & !is.na(crag_value) & (crag_value=="+"),na.rm = TRUE),
        `%crag_pos` = round((crag_pos/crag_done),4)*100
        
      )
  )


###################################  RETURNEES   ###############################
################################################################################
#Outcome : 10, Death(HIV Related), 11: Death (HIV relationship unknown), 
#20: Alive and in care, 30,31: Transfers out
#40,41: LTFUP, 95: Not ascertained
#Def: These are people who have been LTFUP and are coming back to care


returnees<- vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
  filter(
    (visit_dmy>=start_period & visit_dmy<=end_period)
    &(
      #Excludes transfers in and transfers out on the date of visit
      !((visit_dmy == transfer_in_dmy & !is.na(transfer_in_dmy)) #Transfers in
      | ((visit_dmy == outcome_dmy) & ((outcome =="30") |(outcome =="31")))) #30,31 transfers out
    )
    # Filter patients who returned > days for ltfup
    & miss_app_days >days_ltfup 
    )
  
#Filter to get unique patients in reporting period
#Get first occurrence of patient in reporting period

#Q/Consider most recent visit or first occurrence? IMO, most recent as it reflects more recent 
# status of patient
returnees <-returnees%>%
  arrange(patient,desc(visit_dmy))

returnees_dup <-returnees[duplicated(returnees[,pat_col_ind]),]
returnees_data<-returnees[!duplicated(returnees[,pat_col_ind]),]

#Get unique patient codes with no CD4 to be used to avoid duplicate patients
returnees_pat_code <- unique(returnees_data$patient)

#Bind rows to summary data
summ_data_ahd <- summ_data_ahd %>%
  rbind(
    returnees_data %>%
       mutate(
        vis_year = year(visit_dmy)
      )%>%
      mutate(
        category    = "returnees",
      )%>%
      group_by(facility,category) %>%
      summarise(
        eligible    = n(),
        cd4_done    = sum(!is.na(cd4_value),na.rm = TRUE),
        `%cd4_done` = round((cd4_done/eligible),4)*100, 
         cd4_lt200  = sum(cd4_value<200,na.rm = TRUE),
        `%cd4_lt200`= round((cd4_lt200/cd4_done),4)*100,
        lam_done    = sum(cd4_value<200 & !is.na(tbm_value),na.rm = TRUE),
        `%lam_done` = round((lam_done/cd4_lt200),4)*100,
        crag_done   = sum(cd4_value<200 & !is.na(crag_value),na.rm = TRUE),
        `%crag_done`= round((crag_done/cd4_lt200),4)*100,
        lam_pos     = sum(cd4_value<200 & !is.na(tbm_value) & (tbm_value=="+"),na.rm = TRUE),
        `%lam_pos`  = round((lam_pos/lam_done),4)*100,
        crag_pos    = sum(cd4_value<200 & !is.na(crag_value) & (crag_value=="+"),na.rm = TRUE),
        `%crag_pos` = round((crag_pos/crag_done),4)*100
        
      )
  )


#############################  HIGH VIRAL LOAD   ###############################
################################################################################

#Visits with last High VL

#Q/ Consider people with valid CD4 as still part of the cascade for tblam and crag

#Q/Consider most recent visit or first occurence? IMO, most recent as it reflects more recent 
# status of patient
high_vl <-vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
  filter(
    (
      visit_dmy>=start_period & visit_dmy<=end_period) 
      # Filter high VL
      & lastvl_value >1000
    ) %>%
  
  arrange(patient,desc(visit_dmy))

#Unique patients
high_vl_dup<-high_vl[duplicated(high_vl[,pat_col_ind]),]
high_vl_data<-high_vl[!duplicated(high_vl[,pat_col_ind]),]

#Get unique patient codes with no CD4 to be used to avoid duplicate patients
high_vl_pat_code <- unique(high_vl_data$patient)

#Bind rows to summary data
summ_data_ahd <- summ_data_ahd %>%
  rbind(
    high_vl_data %>%
       mutate(
        vis_year = year(visit_dmy)
      )%>%
      mutate(
        category    = "high vl",
      )%>%
      group_by(facility,category) %>%
      summarise(
        eligible    = n(),
        cd4_done    = sum(!is.na(cd4_value),na.rm = TRUE),
        `%cd4_done` = round((cd4_done/eligible),4)*100, 
         cd4_lt200  = sum(cd4_value<200,na.rm = TRUE),
        `%cd4_lt200`= round((cd4_lt200/cd4_done),4)*100,
        lam_done    = sum(cd4_value<200 & !is.na(tbm_value),na.rm = TRUE),
        `%lam_done` = round((lam_done/cd4_lt200),4)*100,
        crag_done   = sum(cd4_value<200 & !is.na(crag_value),na.rm = TRUE),
        `%crag_done`= round((crag_done/cd4_lt200),4)*100,
        lam_pos     = sum(cd4_value<200 & !is.na(tbm_value) & (tbm_value=="+"),na.rm = TRUE),
        `%lam_pos`  = round((lam_pos/lam_done),4)*100,
        crag_pos    = sum(cd4_value<200 & !is.na(crag_value) & (crag_value=="+"),na.rm = TRUE),
        `%crag_pos` = round((crag_pos/crag_done),4)*100
        
      )
  )

############################  PATIENTS WITH NO CD4   ###########################
################################################################################
#Q/ What time window between enrolment in cohort vs check for CD4?
#Joining patient table and lab table(CD4), then filter only patients with no CD4

# Assumption/ Eligibility : Patients enrolled  for >=12M at start of reporting period 
# and never had a CD4 by start of reporting period
# Def : Enrollment date == transfer in if method in art == 1/ art start date if 
# method in art == 0

#Get list of visits within reporting period for patients enrolled for >=12M 
#at the beginning of reporting period

#Get patients who have NEVER done a CD4 prior start of reporting
lab_data_cd4_temp <- lab_data_cd4 %>%
  filter(lab_dmy <start_period)

no_cd4_patient  <- patient_full %>%
  left_join(lab_data_cd4_temp,by = "patient") %>%
  #Get patients who do not have a CD4
  filter(is.na(lab_v))

no_cd4_pat_code <- unique(no_cd4_patient$patient)

#Remove object from memory
rm("lab_data_cd4_temp")

vis_gt_12m <- vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
 
  filter(
      
    #0. Filter only patients who have never done CD4 prior start of reporting period
    patient %in% no_cd4_pat_code
      
    #1. Exclude patients already counted in previous groups
    & !(patient %in% new_init_pat_code)
    & !(patient %in% returnees_pat_code)
    & !(patient %in% high_vl_pat_code)
    
    #2. Filter visits for current reporting period
    &(visit_dmy>=start_period & visit_dmy<=end_period)
    
    #3. Filter patients enrolled for >=12M 
    & ((interval(enrol_date,start_period) %/% days(1) / (365/12)) >12 )
  ) %>%
  
  # Arrange to place first visit for patient with CD4 on top
  # Useful when filtering unique patients
  arrange(desc(patient),desc(cd4_date))

#Get unique patients

no_cd4_data_dup <- vis_gt_12m[duplicated(vis_gt_12m[,6:20]),]

#Patients with no CD4 ever eligibible for CD4 in current reporting period
no_cd4_data <- vis_gt_12m[!duplicated(vis_gt_12m[,6:20]),]

#Get unique patient codes with no CD4 to be used to avoid duplicate patients
no_cd4_pat_code <- unique(no_cd4_data$patient)

#Bind rows to summary data
summ_data_ahd <- summ_data_ahd %>%
  rbind(
    no_cd4_data %>%
       mutate(
        vis_year = year(visit_dmy)
      )%>%
      mutate(
        category    = "patient with no cd4",
      )%>%
      group_by(facility,category) %>%
      summarise(
        eligible    = n(),
        cd4_done    = sum(!is.na(cd4_value),na.rm = TRUE),
        `%cd4_done` = round((cd4_done/eligible),4)*100, 
        cd4_lt200   = sum(cd4_value<200,na.rm = TRUE),
        `%cd4_lt200`= round((cd4_lt200/cd4_done),4)*100,
        lam_done    = sum(cd4_value<200 & !is.na(tbm_value),na.rm = TRUE),
        `%lam_done` = round((lam_done/cd4_lt200),4)*100,
        crag_done   = sum(cd4_value<200 & !is.na(crag_value),na.rm = TRUE),
        `%crag_done`= round((crag_done/cd4_lt200),4)*100,
        lam_pos     = sum(cd4_value<200 & !is.na(tbm_value) & (tbm_value=="+"),na.rm = TRUE),
        `%lam_pos`  = round((lam_pos/lam_done),4)*100,
        crag_pos    = sum(cd4_value<200 & !is.na(crag_value) & (crag_value=="+"),na.rm = TRUE),
        `%crag_pos` = round((crag_pos/crag_done),4)*100
        
      )
  )


#############################  OTHER CD4 DONE   ################################
################################################################################
# This includes all other patients who did CD4 not belonging in any of the eligible 
# categories
other_cd4 <- vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
  filter(
    (
      visit_dmy>=start_period & visit_dmy<=end_period) 
    
      # Exclude patients already list of no CD4 patients
      & !(patient %in% no_cd4_pat_code)
      & !(patient %in% new_init_pat_code)
      & !(patient %in% returnees_pat_code)
      & !(patient %in% high_vl_pat_code)
    ) %>%
  
  arrange(patient,desc(visit_dmy))

#Unique patients
other_cd4_dup <-other_cd4[duplicated(other_cd4[,pat_col_ind]),]
other_cd4_data<-other_cd4[!duplicated(other_cd4[,pat_col_ind]),]

#Get unique patient codes with no CD4 to be used to avoid duplicate patients
other_cd4_pat_code <- unique(other_cd4_data$patient)

#Bind rows to summary data
summ_data_ahd <- summ_data_ahd %>%
  rbind(
    other_cd4_data %>%
       mutate(
        vis_year = year(visit_dmy)
      )%>%
      mutate(
        category    = "Other patients",
      )%>%
      group_by(facility,category) %>%
      summarise(
        eligible    = NA,
        cd4_done    = sum(!is.na(cd4_value),na.rm = TRUE),
        `%cd4_done` = NA, 
        cd4_lt200   = sum(cd4_value<200,na.rm = TRUE),
        `%cd4_lt200`= round((cd4_lt200/cd4_done),4)*100,
        lam_done    = sum(cd4_value<200 & !is.na(tbm_value),na.rm = TRUE),
        `%lam_done` = round((lam_done/cd4_lt200),4)*100,
        crag_done   = sum(cd4_value<200 & !is.na(crag_value),na.rm = TRUE),
        `%crag_done`= round((crag_done/cd4_lt200),4)*100,
        lam_pos     = sum(cd4_value<200 & !is.na(tbm_value) & (tbm_value=="+"),na.rm = TRUE),
        `%lam_pos`  = round((lam_pos/lam_done),4)*100,
        crag_pos    = sum(cd4_value<200 & !is.na(crag_value) & (crag_value=="+"),na.rm = TRUE),
        `%crag_pos` = round((crag_pos/crag_done),4)*100
        
      )
  )


# high_vl_casc<-high_vl_data%>%
#   #Exclude initiations that might be part of the data (cross checking for data quality)
#   filter( 
#     !(visit_dmy == haart_dmy & method_into_art == 0)
#   )%>%
#   #Exclude patients who do not currently have a CD4 but have valid CD4 (<=3M)
#   filter(
#     !(is.na(cd4_value) & !is.na(last3cd4_value))
#   )%>%
#   mutate(
#     quarter_year = quarter(visit_dmy, with_year = T),
#     month_year   = format(as.Date(visit_dmy), "%Y-%m"),
#   )%>%
#   group_by(quarter_year)%>%
#   summarise(
#     tot_hvl        = n(),
#     cd4_hvl        = sum(!is.na(cd4_value)),
#     `% cd4_hvl`    = round((cd4_hvl/tot_hvl),4)*100,
#   )


###### TOTAL OF AHD CASCADE ######
#str(summ_data_ahd)
summ_data_ahd <- summ_data_ahd %>%
  adorn_totals(where = "row")

#Update data in total now
total_row <- tail(summ_data_ahd,1) %>%
  mutate(
    category    = "Total(patient)",
    eligible    = NA,
    `%cd4_done` = NA, 
    `%cd4_lt200`= round((cd4_lt200/cd4_done),4)*100,
    `%lam_done` = round((lam_done/cd4_lt200),4)*100,
    `%crag_done`= round((crag_done/cd4_lt200),4)*100,
    `%lam_pos`  = round((lam_pos/lam_done),4)*100,
    `%crag_pos` = round((crag_pos/crag_done),4)*100
  )

summ_data_ahd[nrow(summ_data_ahd),] <-total_row

## Export generated table into Excel ##

## Create a new workbook
wb <- createWorkbook("AHDDataWorkBook")

## Add a worksheets
openxlsx::addWorksheet(wb, "AHD DATA", gridLines = TRUE)

## write dataframes to worksheets
openxlsx::writeData(wb, sheet = 1, summ_data_ahd,borderStyle = "thin",withFilter = TRUE)

## Save worbook
file_name<-paste("C:\\Users/Gauthier Abdala/Downloads/AHD_PHC",Sys.Date(),".xlsx",sep = "")
openxlsx::saveWorkbook(wb, file_name, overwrite = TRUE)




```
