---
title: "Tiernet"
author: "Gauthier A."
date: "20/04/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# use here from the here package
here <- here::here
# use clean_names from the janitor package
clean_names <- janitor::clean_names

# load functions used from R scripts
source_path <- here("R", "RScripts.R")
source(source_path,local = knitr::knit_global())
#Set vector size limit
memory.limit(size = 4000)

project <- "HIV/Conakry"

data_folder <- "data"
image_folder <- "images"
output_folder <- "output"

start_period <-as.Date("2023/01/01")
end_period   <-as.Date("2023/03/31")

pat_col_ind  <- 4 #Patient column index in the data frame
days_ltfup   <-90 #Days for ltfu. This can be context specific

```

```{r include=FALSE}

#############################################################################
################      I-II. IMPORTING/CLEANING DATA   #######################
#############################################################################

## Note : If your vis table/sheet has more than 600,000 rows,
## You can remove visits that are more than 5 years old to avoid std::bad_alloc error

## Use TierDataCleaning.R if you are analysing data from Tier.net >=1.12
## Change this to point to TierDataCleaningKinshasa.R if you are analysing data from Kinshasa

source(here("R", "TierDataCleaning.R"),local = knitr::knit_global())

```
- No of visits `r length(vis$patient) `
```{r include=FALSE}
#############################################################################
##############      III. Analyzing data/presenting    #######################
#############################################################################
###

#Q/ Do we need a time window for initiations or do we keep strict art_start_date==visit_date


###################### CD4 LAB DATA ##############################
##################################################################
#A/ Given that in Tier.net we encode results dates and not sample collection dates for lab tests, 
# we should have a time window check
#TODO : Need to remove duplicates for CD4 data encoded twice for the same visit


###CD4 Lab Data
lab_data_cd4 <-lab %>%
  filter((lab_id =="CD4A") & !is.na(lab_v)) %>%
  mutate(
    cd4_category = age_categories(
      lab_v,
      breakers = c(0,200,1000)
    )
  )

# lab_cd4<-lab_data_cd4 %>%
#   filter(lab_dmy>as.Date("2022/08/01"))


#vis_cd4 <- left_join(vis_data,lab_data_cd4,c("patient"="patient","visit_dmy"="lab_dmy"))

###!!! Important to clarify CD4 time window (here +-7 days) based on result turnaround time and validity period before requesting
###!!! If there exists two CD4 within the time window, which one to pick? Most recent one?

vis_cd4 <- sqldf(
  "select vis.visit_dmy,vis.patient,vis.next_visit_dmy,vis.folder_number,vis.cohort,vis.facility,vis.birth_dmy,
    vis.gender,vis.frsvis_dmy,vis.haart,vis.haart_dmy,vis.method_into_art,vis.tb_status,vis.transfer_in_dmy,vis.outcome,vis.outcome_dmy,vis.enrol_date,vis.enrol_year,lab.lab_dmy,lab.lab_v,lab.cd4_category 
    from vis_data vis
    left join lab_data_cd4 lab 
      on vis.patient = lab.patient and
        lab.lab_dmy  between (vis.visit_dmy-7)  and (vis.visit_dmy + 7) 
  "
)%>%
  rename(
    cd4_date = lab_dmy,
    cd4_value= lab_v
  )
 
#Filter duplicate lab results based on CD4 lab date
vis_cd4<-vis_cd4 %>%
  arrange(desc(cd4_date))

#Unique visits
#vis_cd4_data_dup<-vis_cd4[duplicated(vis_cd4[,1:16]),]
vis_cd4_data<-vis_cd4[!duplicated(vis_cd4[,1:16]),]

###################### CRAG LAB DATA ##############################
##################################################################


lab_data_crag <-lab %>%
  filter((lab_id =="CRAG") & !is.na(lab_t)) 

vis_cd4_crag <- sqldf(
  "select cd4d.*,crag.lab_dmy,crag.lab_t
    from vis_cd4_data cd4d
    left join lab_data_crag crag
      on cd4d.patient = crag.patient
        and crag.lab_dmy between(cd4d.cd4_date -7) and(cd4d.cd4_date +7)
  "
)%>%
  rename(
    crag_date = lab_dmy,
    crag_value= lab_t
  )

vis_cd4_crag<-vis_cd4_crag %>%
  arrange(desc(crag_date))

#Unique visits
#vis_cd4_crag_data_dup<-vis_cd4_crag[duplicated(vis_cd4_crag[,1:19]),]
vis_cd4_crag_data<-vis_cd4_crag[!duplicated(vis_cd4_crag[,1:19]),]


###################### TBLAM LAB DATA ##############################
####################################################################

lab_data_tblam <-lab %>%
  filter((lab_id =="LAM") & !is.na(lab_t)) 

vis_cd4_crag_tbm <- sqldf(
  "select cd4crag.*,tb.lab_dmy,tb.lab_t
    from vis_cd4_crag_data cd4crag
    left join lab_data_tblam tb
      on cd4crag.patient = tb.patient
        and tb.lab_dmy between(cd4crag.cd4_date -7) and(cd4crag.cd4_date +7)
  "
)%>%
  rename(
    tbm_date = lab_dmy,
    tbm_value= lab_t
  )

vis_cd4_crag_tbm<-vis_cd4_crag_tbm %>%
  arrange(desc(tbm_date))

#Unique visits
#vis_cd4_crag_tbm_data_dup<-vis_cd4_crag_tbm[duplicated(vis_cd4_crag_tbm[,1:21]),]
vis_cd4_crag_tbm_data<-vis_cd4_crag_tbm[!duplicated(vis_cd4_crag_tbm[,1:21]),]


###################### LAST VL DATA #################################
#####################################################################

lab_data_vl <-lab %>%
  filter((lab_id =="RNA") & !is.na(lab_v))

#Get last VL up to 12 months(360 days) before current visit
#Assumption: Validity for a VL is 12 months (1 year)

vis_cd4_crag_tbm_lvl<-sqldf(
  "select data.*,vl.lab_dmy,vl.lab_v
    from vis_cd4_crag_tbm_data data
    left join lab_data_vl vl
      on data.patient = vl.patient
        and vl.lab_dmy between (data.visit_dmy -360) and (data.visit_dmy -1)"
)%>%
  rename(
    lastvl_date = lab_dmy,
    lastvl_value= lab_v
  )

vis_cd4_crag_tbm_lvl<-vis_cd4_crag_tbm_lvl %>%
  arrange(desc(lastvl_date))

#Unique visits
#vis_cd4_crag_tbm_lvl_data_dup<-vis_cd4_crag_tbm_lvl[duplicated(vis_cd4_crag_tbm_lvl[,1:23]),]
vis_cd4_crag_tbm_lvl_data<-vis_cd4_crag_tbm_lvl[!duplicated(vis_cd4_crag_tbm_lvl[,1:23]),]



  
## Remove unused/intermediate objects from memory

rm(list = c("vis_cd4","vis_cd4_data",
            "lab_data_crag","vis_cd4_crag","vis_cd4_crag_data",
            "lab_data_tblam","vis_cd4_crag_tbm","vis_cd4_crag_tbm_data",
            "lab_data_vl","vis_cd4_crag_tbm_lvl"))

###################### LAST CD4 DATA #################################
######################################################################

#Get last CD4 for patient
#Assumption: CD4 within 3 months of current visit may still be valid

vis_cd4_crag_tbm_lvl_l3cd4<-sqldf(
  "
    select data.*,cd4.lab_dmy,cd4.lab_v
    from vis_cd4_crag_tbm_lvl_data data
    left join lab_data_cd4 cd4
      on data.patient = cd4.patient
        and cd4.lab_dmy between (data.visit_dmy -90) and (data.visit_dmy-1)
  "
)%>%
  rename(
    last3cd4_date = lab_dmy,
    last3cd4_value= lab_v
  )

vis_cd4_crag_tbm_lvl_l3cd4<-vis_cd4_crag_tbm_lvl_l3cd4 %>%
  arrange(desc(last3cd4_date))

#Unique visits
#vis_cd4_crag_tbm_lvl_l3cd4_data_dup<-vis_cd4_crag_tbm_lvl_l3cd4[duplicated(vis_cd4_crag_tbm_lvl_l3cd4[,1:25]),]
vis_cd4_crag_tbm_lvl_l3cd4_data<-vis_cd4_crag_tbm_lvl_l3cd4[!duplicated(vis_cd4_crag_tbm_lvl_l3cd4[,1:25]),]

rm(list = c("vis_cd4_crag_tbm_lvl_l3cd4"))

################## LAST NEXT APPOINTMENT DATA ########################
######################################################################

vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_data <- vis_cd4_crag_tbm_lvl_l3cd4_data %>%
  arrange(patient,visit_dmy)%>%
  group_by(patient) %>%
  mutate(# Get previous last next appointment and missed appointment days for patient
    last_next_app = lag(next_visit_dmy),
    miss_app_days = visit_dmy - last_next_app
  ) %>%
  select(last_next_app,visit_dmy,miss_app_days,everything())

#object.size(vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data)
#object.size(vis_cd4_crag_tbm_lvl_l3cd4_data)

########################## TRANSFER DATA #############################
######################################################################
#Add Transfers information to visit data
vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans <-vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_data%>%
  left_join(transfers,c("patient"="patient","visit_dmy"="transfer_dmy"))

vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans<-vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans %>%
  arrange(desc(visit_dmy))%>%
  #Move episode_id at the end
  relocate(episode_id,.after = last_col())

#Remove duplicate lines for transfers
#vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data_dup<-vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans[duplicated(vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans[,1:31]),]
#Note: This will include transfers in and transfers out that happened the same day as two separate lines
vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data<-vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans[!duplicated(vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans[,1:31]),]

#Adding a transfer category, transfer in or out
vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data<- vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data%>%
  mutate(
    trans_cat = case_when(
      mapply(identical,facility,facility_from)  ~ "transfer out",
      mapply(identical,facility,facility_to)  ~ "transfer in",
      TRUE ~ ""
    )
  )

## Remove unused/intermediate objects from memory

rm(list = c("vis","vis_cd4_crag_tbm_lvl_l3cd4","vis_cd4_crag_tbm_lvl_l3cd4_data",
             "vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_data","vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans"))




################################################################################
############################ ELIBILITY CRITERIA ################################
################################################################################


#Summary data for AHD cascade
#If facility included, ncol = 16, if not ncol = 15

col_facility <-"facility"
vis_period   <-"period"
col_names <- c(
              #col_facility,
              "category",
              #vis_period
              "eligible","cd4_done","%cd4_done","cd4_lt200","%cd4_lt200",
               "lam_done","%lam_done","crag_done_","%crag_done","lam_pos","%lam_pos",
               "crag_pos","%crag_pos")

summ_data_ahd <-data.frame(matrix(nrow = 0,ncol=length(col_names)))
colnames(summ_data_ahd) <-col_names

vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data <- vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
  mutate(
    vis_quarter_year = quarter(visit_dmy, with_year = T),
    vis_month_year   = format(as.Date(visit_dmy), "%Y-%m"),
  ) %>%
  filter(
    ## Exclude children with age <5 at the beginning of the period (365*5 = 1825)
     (start_period - birth_dmy ) >=1825
  )


## Get total number of unique patients who visited in the period
vis_period_temp <- vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
  filter(visit_dmy>=start_period & visit_dmy<=end_period )
#tapply(vis_period_temp$patient, vis_period_temp$facility, function(x) length(x))

#vis_period_temp_u <- unique(vis_period_temp$patient)

tot_patient_period <- length(unique (vis_period_temp$patient))
#Remove object from memory
rm(list = c("vis_period_temp"))

###########################  NEW INITIATIONS   #################################
################################################################################

#-Def: Patients initiated in the reporting period(period of observation)
#-Exclusion: Patients who were transferred in

#Filter visits that happen on ART Start Date (new art initiations) and new patients (not transfers in)

new_init <-vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
  filter( 
    (visit_dmy>=start_period & visit_dmy<=end_period)
    ## New initiations filtering
    & (visit_dmy == haart_dmy & method_into_art == 0) 
    
    ## Excludes patients with a valid CD4 (within 3 months)
    &  !(!is.na(last3cd4_value) & is.na(cd4_value))
  )

#Get unique patients data
new_init_data <- new_init[!duplicated(new_init[,6:20]),]

#Get patient codes for new initiations
new_init_pat_code <- unique(new_init_data$patient)

#Bind new initiation data rows to summary data
summ_data_ahd <- summ_data_ahd %>%
  rbind(
    new_init_data %>%
       mutate(
        vis_year = year(visit_dmy)
      )%>%
      mutate(
        category    = "new art initiations",
      )%>%
      group_by(
        #facility,
        category
        #,vis_quarter_year
        ) %>%
      summarise(
        eligible    = n(),
        cd4_done    = sum(!is.na(cd4_value),na.rm = TRUE),
        `%cd4_done` = round((cd4_done/eligible),4)*100, 
        cd4_lt200   = sum(cd4_value<200,na.rm = TRUE),
        `%cd4_lt200`= round((cd4_lt200/cd4_done),4)*100,
        lam_done    = sum(cd4_value<200 & !is.na(tbm_value),na.rm = TRUE),
        `%lam_done` = round((lam_done/cd4_lt200),4)*100,
        crag_done   = sum(cd4_value<200 & !is.na(crag_value),na.rm = TRUE),
        `%crag_done`= round((crag_done/cd4_lt200),4)*100,
        lam_pos     = sum(cd4_value<200 & !is.na(tbm_value) & (tbm_value=="+"),na.rm = TRUE),
        `%lam_pos`  = round((lam_pos/lam_done),4)*100,
        crag_pos    = sum(cd4_value<200 & !is.na(crag_value) & (crag_value=="+"),na.rm = TRUE),
        `%crag_pos` = round((crag_pos/crag_done),4)*100
        
      )
  )



###################################  RETURNEES   ###############################
################################################################################

#-Def : Patients who are returning to care after being LTFU (interrupters). Period of interruption is context specific, here considered 90 days
#-Exclusion :

#Outcome : 10, Death(HIV Related), 11: Death (HIV relationship unknown), 
#20: Alive and in care, 30,31: Transfers out
#40,41: LTFUP, 95: Not ascertained



returnees<- vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
  filter(
    (visit_dmy>=start_period & visit_dmy<=end_period)
    &(
      #Excludes transfers in and transfers out on the date of visit
      !((visit_dmy == transfer_in_dmy & !is.na(transfer_in_dmy)) #Transfers in
      | ((visit_dmy == outcome_dmy) & ((outcome =="30") |(outcome =="31")))) #30,31 transfers out
    )
    # Filter patients who returned > days for ltfup
    & miss_app_days >days_ltfup 
    )
  
#Get first occurrence of patient in reporting period

#Q/Consider most recent visit or first occurrence? IMO, most recent as it reflects more recent 
# status of patient
returnees <-returnees%>%
  arrange(patient,desc(visit_dmy))

returnees_dup <-returnees[duplicated(returnees[,pat_col_ind]),]
returnees_data<-returnees[!duplicated(returnees[,pat_col_ind]),]

#Get unique patient codes for returnees
returnees_pat_code <- unique(returnees_data$patient)

#Bind rows to summary data
summ_data_ahd <- summ_data_ahd %>%
  rbind(
    returnees_data %>%
       mutate(
        vis_year = year(visit_dmy)
      )%>%
      mutate(
        category    = "returnees",
      )%>%
      group_by(
        #facility,
        category
        #,vis_quarter_year
        ) %>%
      summarise(
        eligible    = n(),
        cd4_done    = sum(!is.na(cd4_value),na.rm = TRUE),
        `%cd4_done` = round((cd4_done/eligible),4)*100, 
         cd4_lt200  = sum(cd4_value<200,na.rm = TRUE),
        `%cd4_lt200`= round((cd4_lt200/cd4_done),4)*100,
        lam_done    = sum(cd4_value<200 & !is.na(tbm_value),na.rm = TRUE),
        `%lam_done` = round((lam_done/cd4_lt200),4)*100,
        crag_done   = sum(cd4_value<200 & !is.na(crag_value),na.rm = TRUE),
        `%crag_done`= round((crag_done/cd4_lt200),4)*100,
        lam_pos     = sum(cd4_value<200 & !is.na(tbm_value) & (tbm_value=="+"),na.rm = TRUE),
        `%lam_pos`  = round((lam_pos/lam_done),4)*100,
        crag_pos    = sum(cd4_value<200 & !is.na(crag_value) & (crag_value=="+"),na.rm = TRUE),
        `%crag_pos` = round((crag_pos/crag_done),4)*100
        
      )
  )


#############################  HIGH VIRAL LOAD   ###############################
################################################################################

#-Def : Patients with visiting after a High VL

#Q/ Should we consider people with valid CD4 as still part of the cascade for tblam and crag?

#Q/Should we Consider most recent visit or first occurence? IMO, most recent as it reflects more recent 

# status of patient
high_vl <-vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
  filter(
    (
      visit_dmy>=start_period & visit_dmy<=end_period)
    
      ## Exclude patients who are returnees
      & !(patient %in% returnees_pat_code)
    
      ## Filter high VL
      & lastvl_value >1000 
      
      ## Excludes patients with a valid CD4 (within 3 months)
      &  !(!is.na(last3cd4_value) & is.na(cd4_value))
    ) %>%
  
  arrange(patient,desc(visit_dmy))

#Unique patients
high_vl_dup<-high_vl[duplicated(high_vl[,pat_col_ind]),]
high_vl_data<-high_vl[!duplicated(high_vl[,pat_col_ind]),]

#Get unique patient codes for High VL
high_vl_pat_code <- unique(high_vl_data$patient)

#Bind rows to summary data
summ_data_ahd <- summ_data_ahd %>%
  rbind(
    high_vl_data %>%
       mutate(
        vis_year = year(visit_dmy)
      )%>%
      mutate(
        category    = "high vl",
      )%>%
      group_by(
        #facility,
        category
        #,vis_quarter_year
        ) %>%
      summarise(
        eligible    = n() ,
        cd4_done    = sum(!is.na(cd4_value),na.rm = TRUE),
        `%cd4_done` = round((cd4_done/eligible),4)*100, 
         cd4_lt200  = sum(cd4_value<200,na.rm = TRUE),
        `%cd4_lt200`= round((cd4_lt200/cd4_done),4)*100,
        lam_done    = sum(cd4_value<200 & !is.na(tbm_value),na.rm = TRUE),
        `%lam_done` = round((lam_done/cd4_lt200),4)*100,
        crag_done   = sum(cd4_value<200 & !is.na(crag_value),na.rm = TRUE),
        `%crag_done`= round((crag_done/cd4_lt200),4)*100,
        lam_pos     = sum(cd4_value<200 & !is.na(tbm_value) & (tbm_value=="+"),na.rm = TRUE),
        `%lam_pos`  = round((lam_pos/lam_done),4)*100,
        crag_pos    = sum(cd4_value<200 & !is.na(crag_value) & (crag_value=="+"),na.rm = TRUE),
        `%crag_pos` = round((crag_pos/crag_done),4)*100
        
      )
  )

############################  PATIENTS WITH NO CD4   ###########################
################################################################################
#Q/ What time window between enrolment in cohort vs check for CD4?
#Joining patient table and lab table(CD4), then filter only patients with no CD4

#-Def : Patients enrolled  for >=12M at start of reporting period 
# and never had a CD4 by start of reporting period
# Assumption : Enrollment date == transfer in if method in art == 1/ art start date if method in art == 0

#Get list of visits within reporting period for patients enrolled for >=12M 
#at the beginning of reporting period

#Get patients who have NEVER done a CD4 prior start of reporting
lab_data_cd4_temp <- lab_data_cd4 %>%
  filter(lab_dmy <start_period)

no_cd4_patient  <- patient_data %>%
  left_join(lab_data_cd4_temp,by = "patient") %>%
  
  #Get patients who do not have a CD4
  filter(is.na(lab_v))

no_cd4_pat_code <- unique(no_cd4_patient$patient)

#Remove object from memory
rm("lab_data_cd4_temp")

vis_gt_12m <- vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
  
  filter(
      
    #0. Filter only patients who have never done CD4 prior start of reporting period
    patient %in% no_cd4_pat_code
      
    #1. Exclude patients already counted in previous groups
    & !(patient %in% new_init_pat_code)
    & !(patient %in% returnees_pat_code)
    & !(patient %in% high_vl_pat_code)
    
    #2. Filter visits for current reporting period
    &(visit_dmy>=start_period & visit_dmy<=end_period)
    
    #3. Filter patients enrolled for >=12M 
    & ((interval(enrol_date,start_period) %/% days(1) / (365/12)) >12 )
  ) %>%
  
  # Arrange to place first visit for patient with CD4 on top
  # Useful when filtering unique patients
  arrange(desc(patient),desc(cd4_date))

#Get unique patients

no_cd4_data_dup <- vis_gt_12m[duplicated(vis_gt_12m[,6:20]),]

#Patients with no CD4 ever eligibible for CD4 in current reporting period
no_cd4_data <- vis_gt_12m[!duplicated(vis_gt_12m[,6:20]),]

#Get unique patient codes with no CD4 
no_cd4_pat_code <- unique(no_cd4_data$patient)

#Bind rows to summary data
summ_data_ahd <- summ_data_ahd %>%
  rbind(
    no_cd4_data %>%
       mutate(
        vis_year = year(visit_dmy)
      )%>%
      mutate(
        category    = "patient with no cd4",
      )%>%
      group_by(
        #facility,
        category
        #,vis_quarter_year
        ) %>%
      summarise(
        eligible    = n(),
        cd4_done    = sum(!is.na(cd4_value),na.rm = TRUE),
        `%cd4_done` = round((cd4_done/eligible),4)*100, 
        cd4_lt200   = sum(cd4_value<200,na.rm = TRUE),
        `%cd4_lt200`= round((cd4_lt200/cd4_done),4)*100,
        lam_done    = sum(cd4_value<200 & !is.na(tbm_value),na.rm = TRUE),
        `%lam_done` = round((lam_done/cd4_lt200),4)*100,
        crag_done   = sum(cd4_value<200 & !is.na(crag_value),na.rm = TRUE),
        `%crag_done`= round((crag_done/cd4_lt200),4)*100,
        lam_pos     = sum(cd4_value<200 & !is.na(tbm_value) & (tbm_value=="+"),na.rm = TRUE),
        `%lam_pos`  = round((lam_pos/lam_done),4)*100,
        crag_pos    = sum(cd4_value<200 & !is.na(crag_value) & (crag_value=="+"),na.rm = TRUE),
        `%crag_pos` = round((crag_pos/crag_done),4)*100
        
      )
  )


#############################  OTHER CD4 DONE   ################################
################################################################################
# This includes all other patients who did CD4 not belonging in any of the eligible 
# categories
other_cd4 <- vis_cd4_crag_tbm_lvl_l3cd4_lstnxtapp_trans_data %>%
  filter(
    (
      visit_dmy>=start_period & visit_dmy<=end_period) 
    
      # Exclude patients already list of no CD4 patients
      & !(patient %in% no_cd4_pat_code)
      & !(patient %in% new_init_pat_code)
      & !(patient %in% returnees_pat_code)
      & !(patient %in% high_vl_pat_code)
    ) %>%
  
  arrange(patient,desc(visit_dmy))

#Unique patients
other_cd4_dup <-other_cd4[duplicated(other_cd4[,pat_col_ind]),]
other_cd4_data<-other_cd4[!duplicated(other_cd4[,pat_col_ind]),]

#Get unique patient codes with no CD4 
other_cd4_pat_code <- unique(other_cd4_data$patient)

#Bind rows to summary data
summ_data_ahd <- summ_data_ahd %>%
  rbind(
    other_cd4_data %>%
       mutate(
        vis_year = year(visit_dmy)
      )%>%
      mutate(
        category    = "Other patients",
      )%>%
      group_by(
        #facility,
        category
        #,vis_quarter_year
        ) %>%
      summarise(
        eligible    = NA,
        cd4_done    = sum(!is.na(cd4_value),na.rm = TRUE),
        `%cd4_done` = NA, 
        cd4_lt200   = sum(cd4_value<200,na.rm = TRUE),
        `%cd4_lt200`= round((cd4_lt200/cd4_done),4)*100,
        lam_done    = sum(cd4_value<200 & !is.na(tbm_value),na.rm = TRUE),
        `%lam_done` = round((lam_done/cd4_lt200),4)*100,
        crag_done   = sum(cd4_value<200 & !is.na(crag_value),na.rm = TRUE),
        `%crag_done`= round((crag_done/cd4_lt200),4)*100,
        lam_pos     = sum(cd4_value<200 & !is.na(tbm_value) & (tbm_value=="+"),na.rm = TRUE),
        `%lam_pos`  = round((lam_pos/lam_done),4)*100,
        crag_pos    = sum(cd4_value<200 & !is.na(crag_value) & (crag_value=="+"),na.rm = TRUE),
        `%crag_pos` = round((crag_pos/crag_done),4)*100
        
      )
  )


###### TOTAL OF AHD CASCADE ######
#str(summ_data_ahd)
summ_data_ahd <- summ_data_ahd %>%
  adorn_totals(where = "row")

#Update data in total now
total_row <- tail(summ_data_ahd,1) %>%
  mutate(
    #facility    = "All",
    category    = "Total(patient)",
    #vis_quarter_year= NA,
    eligible    = NA,
    `%cd4_done` = NA, 
    `%cd4_lt200`= round((cd4_lt200/cd4_done),4)*100,
    `%lam_done` = round((lam_done/cd4_lt200),4)*100,
    `%crag_done`= round((crag_done/cd4_lt200),4)*100,
    `%lam_pos`  = round((lam_pos/lam_done),4)*100,
    `%crag_pos` = round((crag_pos/crag_done),4)*100
  )

summ_data_ahd[nrow(summ_data_ahd),] <-total_row
```

```{r include=FALSE}
## Create a new workbook
wb <- createWorkbook("TierAnalysisAHD")

## Variables to include in the export
cols_export <-c("visit_dmy","next_visit_dmy","folder_number","facility","birth_dmy","haart_dmy","cd4_date","cd4_value","cd4_category","crag_date","crag_value","tbm_date","tbm_value","lastvl_date","lastvl_value","last3cd4_date","last3cd4_value")


## Add a worksheets
openxlsx::addWorksheet(wb, "NewInitiation", gridLines = TRUE)
openxlsx::addWorksheet(wb, "CV elevé", gridLines = TRUE)
openxlsx::addWorksheet(wb, "Interrupteurs", gridLines = TRUE)
openxlsx::addWorksheet(wb, "Sans CD4", gridLines = TRUE)
openxlsx::addWorksheet(wb, "Sommaire", gridLines = TRUE)
## write dataframes to worksheets
openxlsx::writeData(wb, sheet = 1, new_init_data %>% select(cols_export),borderStyle = "thin",withFilter = TRUE)
openxlsx::writeData(wb, sheet = 2, high_vl_data %>% select(cols_export),borderStyle = "thin",withFilter = TRUE)
openxlsx::writeData(wb, sheet = 3, returnees_data %>% select(cols_export),borderStyle = "thin",withFilter = TRUE)
openxlsx::writeData(wb, sheet = 4, no_cd4_data %>% select(cols_export),borderStyle = "thin",withFilter = TRUE)
openxlsx::writeData(wb, sheet = 5, summ_data_ahd,borderStyle = "thin",withFilter = TRUE)

file_name<-paste(here("output/TierAHD_"),Sys.Date(),".xlsx",sep = "")

openxlsx::saveWorkbook(wb, file_name, overwrite = TRUE)

```

```{r include=FALSE}
############ GENERATING GRAPHS AND TABLES FOR PRESENTATION  ##############
##########################################################################
diagram_title <-c(paste('PHC AHD Cascade - ',project,', ',start_period,'to',end_period))


DiagrammeR::grViz(
  "digraph ahdcascade{
  
    graph[layout = dot,
          labelloc='t' , # Title location as 't'op
          label='@@18', # Diagram title
          fontsize = 24] # Title font size
    
    # define the global styles of the nodes. We can override these in box if we wish
    node [shape = rectangle, width=4, style = filled, fillcolor = white,fontsize = 20]
    
    vis      [label = '@@1']
    newinit  [label = '@@2' fillcolor = MistyRose]
    highvl   [label = '@@3' fillcolor = AntiqueWhite]
    returnee [label = '@@4' fillcolor = LemonChiffon]
    nocd4    [label = '@@5' fillcolor = Beige]
    others   [label = '@@6' fillcolor = MintCream]
    
    newinitcd4 [label = '@@7' fillcolor = MistyRose]
    highvlcd4  [label = '@@8' fillcolor = AntiqueWhite]
    returneecd4[label = '@@9' fillcolor = LemonChiffon]
    nocd4cd4   [label = '@@10' fillcolor = Beige]
    otherscd4  [label = '@@11' fillcolor = MintCream]
    
    totcd4  [label = '@@12'  fillcolor = PaleGreen]
    
    totcd4lt200 [label = '@@13' fillcolor = Coral]
    
    lam [label = '@@14']
    crag[label = '@@15']
    
    lampos [label = '@@16']
    cragpos[label = '@@17']
    
    ## Associations for diagrams
    vis -> {newinit, highvl,returnee,nocd4,others}
    
    newinit  -> newinitcd4
    highvl   -> highvlcd4
    returnee -> returneecd4
    nocd4    -> nocd4cd4
    others   -> otherscd4
    
  {newinitcd4,highvlcd4,returneecd4,nocd4cd4,otherscd4} -> totcd4
  
  totcd4 -> totcd4lt200
  
  totcd4lt200 ->{lam,crag}
  lam  ->lampos
  crag ->cragpos
  
  }
  
  [1]: paste0('Patients \\n',tot_patient_period) 
  [2]: paste0('New ART initiations','\\n',summ_data_ahd[[1,2]])
  [3]: paste0('Returnees','\\n',summ_data_ahd[[2,2]])
  [4]: paste0('High VL','\\n',summ_data_ahd[[3,2]])
  [5]: paste0('No CD4','\\n',summ_data_ahd[[4,2]])
  [6]: paste0('Others (clinical signs...)','\\n ')
  [7]: paste0(' % CD4 done (',summ_data_ahd[[1,4]],') \\n',summ_data_ahd[[1,3]],'/',summ_data_ahd[[1,2]])
  [8]: paste0(' % CD4 done (',summ_data_ahd[[2,4]],') \\n',summ_data_ahd[[2,3]],'/',summ_data_ahd[[2,2]])
  [9]: paste0(' % CD4 done (',summ_data_ahd[[3,4]],') \\n',summ_data_ahd[[3,3]],'/',summ_data_ahd[[3,2]])
  [10]: paste0(' % CD4 done (',summ_data_ahd[[4,4]],') \\n',summ_data_ahd[[4,3]],'/',summ_data_ahd[[4,2]])
  [11]: paste0(' # CD4 done (','NA',') \\n',summ_data_ahd[[5,3]])
  [12]: paste0(' #Total CD4 done(Patient)','\\n',summ_data_ahd[[6,3]])
  [13]: paste0(' % CD4<200 (',summ_data_ahd[[6,6]],') \\n',summ_data_ahd[[6,5]],'/',summ_data_ahd[[6,3]])
  [14]: paste0(' %Tblam done (',summ_data_ahd[[6,8]],') \\n',summ_data_ahd[[6,7]],'/',summ_data_ahd[[6,5]])
  [15]: paste0(' %Crag done (',summ_data_ahd[[6,10]],') \\n',summ_data_ahd[[6,9]],'/',summ_data_ahd[[6,5]])
  [16]: paste0(' %Tblam +(',summ_data_ahd[[6,12]],') \\n',summ_data_ahd[[6,11]],'/',summ_data_ahd[[6,7]])
  [17]: paste0(' %Crag +(',summ_data_ahd[[6,14]],') \\n',summ_data_ahd[[6,13]],'/',summ_data_ahd[[6,9]])
  [18]: paste0(diagram_title,'\\n \\n')"
  ) %>%
  
  ## Export the cascade into an image in the output folder
  export_svg %>% charToRaw %>% rsvg::rsvg_png(paste(here("output/ahd_cascade_"),Sys.Date(),".png",sep = ""))
  ##export_graph(file_name = "test.png")


# tapply(new_init_data$patient, new_init_data$facility, function(x) length(x))
# 
# lab_test <- lab_data_cd4 %>%
#   filter(lab_dmy>=as.Date("2022-01-01") & lab_dmy<=as.Date("2022-06-30")) %>%
#   arrange(desc(lab_dmy))
# 
# lab_test <-lab_test[!duplicated(lab_test[,1]),]
# lab_test%>%
#   group_by(cd4_category)%>%
#   
#   summarise(
#     tot =n()
#   )


```
